# Generated by Django 6.0.3 on 2026-05-22 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='audio_file',
            field=models.FileField(default='test.mp3', upload_to='songs/'),
            preserve_default=False,
        ),
    ]
