# Generated by Django 6.0.3 on 2026-05-25 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='cover_image',
            field=models.ImageField(default='default.jpg', upload_to='covers/'),
            preserve_default=False,
        ),
    ]
