# Generated by Django 6.0.5 on 2026-05-28 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_emailotp_delete_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(blank=True, to='music.song'),
        ),
    ]
